# Comandos para filtrar algumas informações do DataFame

## - Tirando /São Paulo
## - Adicionando Coluna de zonas
## - Classificando cada bairro em zonas da cidade de São Paulo

In [1]:
%matplotlib inline
%reset -f
import math
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm, uniform, probplot
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [2]:
#Definir seed
RANDOM_SEED = 69

In [3]:
#Abrindo a base de dados 

data = pd.read_csv("sao-paulo-properties-april-2019.csv")
data.drop(data.columns[[15, 14]], axis=1, inplace=True)

In [12]:
#Zonas de São Paulo

zona_sul = ['Campo Limpo', 'Capão Redondo', 'Vila Andrade', 'Cidade Dutra', 'Grajaú', 'Socorro', 'Cidade Ademar', 'Pedreira', 'Ipiranga', 'Sacomã', 'Jabaquara', "M'Boi Mirim", 'Jardim Ângela', 'Jardim Sao Luis', 'Parelheiros', 'Marsilac', 'Santo Amaro', 'Campo Belo', 'Campo Grande', 'Moema', 'Saúde', 'Vila Mariana', 'Brooklin', 'Vila Olimpia', 'Cursino', 'Jardim São Luis']
zona_leste = ['Aricanduva', 'Carrão', 'Vila Formosa', 'Cidade Tiradentes', 'Ermelino Matarazzo', 'Ponte Rasa', 'Guaianases', 'Lajeado', 'Itaim Paulista', 'Vila Curuça', 'Itaquera', 'Cidade Lider', 'José Bonifácio', 'Parque do Carmo', 'Mooca Água Rasa', 'Belém', 'Brás', 'Mooca', 'Pari', 'Tatuapé', 'Penha', 'Artur Alvim', 'Cangaíba', 'Penha', 'Vila Matilde', 'São Mateus', 'São Rafael', 'São Miguel', 'Jardim Helena', 'Vila Jacuí', 'Sapopemba', 'Vila Prudente', 'São Lucas', 'Água Rasa', 'Vila Curuçá', 'Cidade Líder', 'Guaianazes', 'Iguatemi'] 
zona_oeste = ['Butantã', 'Morumbi', 'Raposo Tavares', 'Rio Pequeno', 'Vila Sônia', 'Lapa', 'Barra Funda', 'Jaguara', 'Jaguaré', 'Perdizes', 'Vila Leopoldina', 'Pinheiros', 'Alto de Pinheiros', 'Itaim Bibi', 'Jardim Paulista', 'Pinheiros', 'Vila Madalena']
zona_norte = ['Casa Verde', 'Cachoeirinha', 'Limão', 'Brasilândia', 'Freguesia do Ó', 'Jaçanã', 'Tremembé', 'Perus', 'Anhanguera', 'Pirituba', 'Jaraguá', 'São Domingos', 'Santana', 'Tucuruvi', 'Mandaqui', 'Vila Maria', 'Vila Guilherme', 'Vila Medeiros', 'Medeiros']
centro = ['Sé Bela Vista', 'Bela Vista', 'Bom Retiro', 'Cambuci', 'Consolação', 'Liberdade', 'República', 'Santa Cecília', 'Sé']

In [13]:
#Tirando /São Paulo dos bairros

filtro = data.District.str.replace('/São Paulo', '')
filtro
data.District = filtro

In [14]:
#Adicionando zonas em função dos bairros para cada item do DataFrame

data.loc[(data.District).isin (zona_sul), 'Zone'] = 'ZS'
data.loc[(data.District).isin (zona_leste), 'Zone'] = 'ZL'
data.loc[(data.District).isin (zona_oeste), 'Zone'] = 'ZO'
data.loc[(data.District).isin (zona_norte), 'Zone'] = 'ZN'
data.loc[(data.District).isin (centro), 'Zone'] = 'Centro'

In [15]:
data

,Price,Condo,Size,Rooms,Toilets,Suites,Parking,Elevator,Furnished,Swimming Pool,New,District,Negotiation Type,Property Type,Zone
0,930,220,47,2,2,1,1,0,0,0,0,Artur Alvim,rent,apartment,ZL
1,1000,148,45,2,2,1,1,0,0,0,0,Artur Alvim,rent,apartment,ZL
2,1000,100,48,2,2,1,1,0,0,0,0,Artur Alvim,rent,apartment,ZL
3,1000,200,48,2,2,1,1,0,0,0,0,Artur Alvim,rent,apartment,ZL
4,1300,410,55,2,2,1,1,1,0,0,0,Artur Alvim,rent,apartment,ZL
5,1170,0,50,2,2,1,1,0,0,0,0,Artur Alvim,rent,apartment,ZL
6,1000,180,52,1,2,1,1,1,0,0,0,Artur Alvim,rent,apartment,ZL
7,900,150,40,2,2,1,1,0,0,0,0,Artur Alvim,rent,apartment,ZL
8,1000,0,65,2,2,1,1,0,0,0,0,Artur Alvim,rent,apartment,ZL
9,1000,0,100,2,2,1,1,0,0,0,0,Artur Alvim,rent,apartment,ZL
10,760,160,38,2,2,1,1,0,0,0,0,Artur Alvim,rent,apartment,ZL
11,800,150,48,2,2,1,1,0,0,0,0,Artur Alvim,rent,apartment,ZL
12,900,130,56,2,2,1,1,0,0,0,0,Artur Alvim,rent,apartment,ZL
13,1000,200,56,2,2,1,1,0,0,0,0,Artur Alvim,rent,apartment,ZL
14,1800,418,54,2,2,1,1,1,0,1,0,Belém,rent,apartment,ZL
15,1600,416,45,2,2,1,1,0,0,0,0,Belém,rent,apartment,ZL
16,1500,337,55,2,2,1,1,1,0,0,0,Belém,rent,apartment,ZL
17,1600,306,43,2,2,1,1,1,0,0,0,Belém,rent,apartment,ZL
18,1600,150,80,2,2,1,1,1,0,0,0,Belém,rent,apartment,ZL
19,1600,420,46,2,2,1,1,0,0,0,0,Belém,rent,apartment,ZL
20,1900,800,67,3,2,1,1,1,1,0,0,Belém,rent,apartment,ZL
21,2500,720,68,3,2,1,1,0,0,1,0,Belém,rent,apartment,ZL
22,1400,743,63,2,2,1,1,0,0,1,0,Belém,rent,apartment,ZL
23,1800,530,59,3,2,1,1,0,0,0,0,Belém,rent,apartment,ZL
24,1500,2893,230,3,2,1,2,0,0,0,0,Belém,rent,apartment,ZL
25,2300,857,113,3,2,1,2,1,0,0,0,Belém,rent,apartment,ZL
26,2250,530,68,2,2,1,1,0,0,1,0,Belém,rent,apartment,ZL
27,1700,445,65,2,2,1,1,0,0,1,0,Belém,rent,apartment,ZL
28,1726,290,55,2,2,1,1,1,0,1,0,Belém,rent,apartment,ZL
29,1700,450,50,1,2,1,1,1,0,1,0,Belém,rent,apartment,ZL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13610,299000,316,51,1,1,0,1,0,0,0,0,Jabaquara,sale,apartment,ZS
13611,590000,600,75,3,2,1,2,0,1,1,0,Jabaquara,sale,apartment,ZS
13612,500000,400,67,3,2,1,1,0,0,1,0,Jabaquara,sale,apartment,ZS
13613,350000,560,62,3,2,1,1,0,0,0,0,Jabaquara,sale,apartment,ZS
13614,330000,615,49,2,1,0,1,0,0,0,0,Jabaquara,sale,apartment,ZS
13615,725000,625,86,3,2,1,3,0,0,1,0,Jabaquara,sale,apartment,ZS
13616,340000,401,64,2,1,0,1,0,0,0,0,Jabaquara,sale,apartment,ZS
13617,370000,620,55,2,1,0,1,1,0,1,0,Jabaquara,sale,apartment,ZS
13618,455000,650,70,2,1,0,1,0,0,1,0,Jabaquara,sale,apartment,ZS
13619,425000,521,64,3,1,0,1,0,0,1,0,Jabaquara,sale,apartment,ZS
13620,360000,803,63,2,1,0,1,0,0,0,0,Jabaquara,sale,apartment,ZS
13621,630000,450,91,3,2,1,2,0,0,1,0,Jabaquara,sale,apartment,ZS
13622,290000,470,40,1,1,0,1,0,0,0,0,Jabaquara,sale,apartment,ZS
13623,230000,528,52,2,1,0,0,0,0,0,0,Jabaquara,sale,apartment,ZS
13624,490000,745,63,2,2,1,2,1,0,0,0,Jabaquara,sale,apartment,ZS
13625,280000,505,52,2,1,0,1,0,0,1,0,Jabaquara,sale,apartment,ZS
13626,595000,1250,114,3,2,1,2,0,0,1,0,Jabaquara,sale,apartment,ZS
13627,530000,580,73,3,2,1,2,0,0,0,0,Jabaquara,sale,apartment,ZS
13628,299000,580,53,2,1,0,1,0,0,0,0,Jabaquara,sale,apartment,ZS
13629,995000,860,102,3,2,1,2,0,0,1,0,Jabaquara,sale,apartment,ZS
13630,280000,480,55,2,1,0,1,0,0,0,0,Jabaquara,sale,apartment,ZS
13631,350000,554,68,2,1,0,1,0,0,0,0,Jabaquara,sale,apartment,ZS
13632,800000,996,86,3,2,1,2,0,0,1,0,Jabaquara,sale,apartment,ZS
13633,300000,370,47,2,1,0,1,0,0,0,0,Jabaquara,sale,apartment,ZS
13634,456000,770,85,3,1,0,1,0,0,0,0,Jabaquara,sale,apartment,ZS
13635,265000,420,51,2,1,0,1,0,0,0,0,Jabaquara,sale,apartment,ZS
13636,545000,630,74,3,2,1,2,0,0,1,0,Jabaquara,sale,apartment,ZS
13637,515000,1100,114,3,3,1,1,0,0,1,0,Jabaquara,sale,apartment,ZS
13638,345000,48,39,1,2,1,1,0,1,1,0,Jabaquara,sale,apartment,ZS
13639,161987,0,44,2,1,0,1,0,0,0,0,Jardim Ângela,sale,apartment,ZS

In [16]:
data.Zone.value_counts()

ZL        4161
ZS        3085
ZO        2607
ZN        2164
Centro    1623
Name: Zone, dtype: int64

In [17]:
data.District.value_counts()

Moema                293
Mooca                288
Brás                 255
Brooklin             250
Bela Vista           250
Pinheiros            249
Casa Verde           248
Cambuci              241
Perdizes             236
Alto de Pinheiros    230
Vila Prudente        221
Itaim Bibi           220
Bom Retiro           220
Consolação           218
Jardim Paulista      218
Liberdade            216
Campo Grande         210
Santa Cecília        209
Belém                205
Vila Mariana         204
Ipiranga             201
Tatuapé              194
Barra Funda          194
Mandaqui             193
Morumbi              193
Jabaquara            191
Carrão               188
Santo Amaro          184
Campo Belo           184
Vila Leopoldina      184
                    ...
Cidade Tiradentes     95
Vila Jacuí            92
Sé                    90
Cachoeirinha          89
Capão Redondo         89
Cidade Dutra          88
José Bonifácio        87
Medeiros              86
Tremembé              85
Vila Olimpia          84
Brasilândia           84
Pari                  83
Parque do Carmo       83
Jaraguá               75
Guaianazes            75
Anhanguera            75
Jardim Ângela         75
Ponte Rasa            67
Itaim Paulista        66
Iguatemi              65
Jardim Helena         61
São Miguel            60
Pedreira              59
Raposo Tavares        52
Lajeado               47
Jardim São Luis       44
São Rafael            44
Grajaú                37
São Domingos          35
Perus                 30
Name: District, Length: 96, dtype: int64

In [18]:
data.Zone.isnull().sum()

0

In [19]:
data.District[data.Zone.isnull()].value_counts()

Series([], Name: District, dtype: int64)